import type {
  Activity,
  Client,
  DashboardStats,
  Deal,
  Lead,
  Property,
  Task,
} from "@/types"

export const dashboardStats: DashboardStats = {
  totalProperties: 48,
  activeLeads: 127,
  closedDeals: 23,
  monthlyRevenue: 2840000,
  propertiesChange: 12,
  leadsChange: 8,
  dealsChange: 15,
  revenueChange: 22,
}

export const properties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Loft",
    address: "142 Market Street",
    city: "San Francisco, CA",
    price: 1250000,
    beds: 2,
    baths: 2,
    sqft: 1450,
    status: "available",
    type: "Apartment",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    agent: "Sarah Chen",
    listedAt: "2026-03-01",
  },
  {
    id: "2",
    title: "Coastal Family Home",
    address: "88 Ocean View Drive",
    city: "Malibu, CA",
    price: 3200000,
    beds: 5,
    baths: 4,
    sqft: 4200,
    status: "pending",
    type: "House",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop",
    agent: "Michael Torres",
    listedAt: "2026-02-15",
  },
  {
    id: "3",
    title: "Urban Studio Apartment",
    address: "55 West 23rd Street",
    city: "New York, NY",
    price: 680000,
    beds: 1,
    baths: 1,
    sqft: 750,
    status: "available",
    type: "Apartment",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop",
    agent: "Sarah Chen",
    listedAt: "2026-03-10",
  },
  {
    id: "4",
    title: "Suburban Estate",
    address: "2100 Maple Lane",
    city: "Austin, TX",
    price: 890000,
    beds: 4,
    baths: 3,
    sqft: 3100,
    status: "sold",
    type: "House",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop",
    agent: "Emily Watson",
    listedAt: "2026-01-20",
  },
  {
    id: "5",
    title: "Lakefront Villa",
    address: "7 Lakeside Court",
    city: "Lake Tahoe, CA",
    price: 2100000,
    beds: 4,
    baths: 3,
    sqft: 3800,
    status: "available",
    type: "Villa",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop",
    agent: "Michael Torres",
    listedAt: "2026-03-05",
  },
  {
    id: "6",
    title: "Historic Brownstone",
    address: "334 Beacon Street",
    city: "Boston, MA",
    price: 1750000,
    beds: 3,
    baths: 2,
    sqft: 2200,
    status: "off-market",
    type: "Townhouse",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop",
    agent: "Emily Watson",
    listedAt: "2025-12-01",
  },
]

export const leads: Lead[] = [
  {
    id: "1",
    name: "James Rodriguez",
    email: "james.r@email.com",
    phone: "+1 (415) 555-0142",
    source: "Website",
    status: "new",
    propertyInterest: "Modern Downtown Loft",
    budget: 1300000,
    createdAt: "2026-03-18",
    assignedTo: "Sarah Chen",
  },
  {
    id: "2",
    name: "Lisa Park",
    email: "lisa.park@email.com",
    phone: "+1 (212) 555-0198",
    source: "Referral",
    status: "qualified",
    propertyInterest: "Urban Studio Apartment",
    budget: 750000,
    createdAt: "2026-03-15",
    assignedTo: "Sarah Chen",
  },
  {
    id: "3",
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "+1 (310) 555-0234",
    source: "Open House",
    status: "negotiation",
    propertyInterest: "Coastal Family Home",
    budget: 3000000,
    createdAt: "2026-03-10",
    assignedTo: "Michael Torres",
  },
  {
    id: "4",
    name: "Amanda Foster",
    email: "amanda.f@email.com",
    phone: "+1 (512) 555-0167",
    source: "Social Media",
    status: "contacted",
    propertyInterest: "Suburban Estate",
    budget: 950000,
    createdAt: "2026-03-12",
    assignedTo: "Emily Watson",
  },
  {
    id: "5",
    name: "Robert Hayes",
    email: "robert.h@email.com",
    phone: "+1 (617) 555-0289",
    source: "Website",
    status: "closed",
    propertyInterest: "Historic Brownstone",
    budget: 1800000,
    createdAt: "2026-02-28",
    assignedTo: "Emily Watson",
  },
]

export const clients: Client[] = [
  {
    id: "1",
    name: "Jennifer Walsh",
    email: "j.walsh@email.com",
    phone: "+1 (415) 555-0301",
    type: "buyer",
    totalDeals: 3,
    totalValue: 4200000,
    lastContact: "2026-03-17",
  },
  {
    id: "2",
    name: "Thomas Anderson",
    email: "t.anderson@email.com",
    phone: "+1 (310) 555-0312",
    type: "seller",
    totalDeals: 2,
    totalValue: 5800000,
    lastContact: "2026-03-16",
  },
  {
    id: "3",
    name: "Maria Gonzalez",
    email: "maria.g@email.com",
    phone: "+1 (212) 555-0323",
    type: "investor",
    totalDeals: 8,
    totalValue: 12500000,
    lastContact: "2026-03-18",
  },
  {
    id: "4",
    name: "Kevin O'Brien",
    email: "kevin.ob@email.com",
    phone: "+1 (512) 555-0334",
    type: "buyer",
    totalDeals: 1,
    totalValue: 890000,
    lastContact: "2026-03-14",
  },
  {
    id: "5",
    name: "Sophie Laurent",
    email: "sophie.l@email.com",
    phone: "+1 (617) 555-0345",
    type: "seller",
    totalDeals: 4,
    totalValue: 7200000,
    lastContact: "2026-03-12",
  },
]

export const deals: Deal[] = [
  {
    id: "1",
    title: "Downtown Loft Sale",
    client: "Jennifer Walsh",
    property: "Modern Downtown Loft",
    value: 1250000,
    stage: "negotiation",
    probability: 75,
    closeDate: "2026-04-15",
    agent: "Sarah Chen",
  },
  {
    id: "2",
    title: "Coastal Home Purchase",
    client: "David Kim",
    property: "Coastal Family Home",
    value: 3200000,
    stage: "proposal",
    probability: 60,
    closeDate: "2026-05-01",
    agent: "Michael Torres",
  },
  {
    id: "3",
    title: "Suburban Estate Deal",
    client: "Kevin O'Brien",
    property: "Suburban Estate",
    value: 890000,
    stage: "closed",
    probability: 100,
    closeDate: "2026-03-10",
    agent: "Emily Watson",
  },
  {
    id: "4",
    title: "Lakefront Villa Inquiry",
    client: "Maria Gonzalez",
    property: "Lakefront Villa",
    value: 2100000,
    stage: "prospect",
    probability: 30,
    closeDate: "2026-06-30",
    agent: "Michael Torres",
  },
  {
    id: "5",
    title: "Studio Apartment Sale",
    client: "Lisa Park",
    property: "Urban Studio Apartment",
    value: 680000,
    stage: "negotiation",
    probability: 80,
    closeDate: "2026-04-01",
    agent: "Sarah Chen",
  },
]

export const activities: Activity[] = [
  {
    id: "1",
    type: "viewing",
    title: "Property viewing scheduled",
    description: "James Rodriguez — Modern Downtown Loft",
    time: "2 hours ago",
    user: "Sarah Chen",
  },
  {
    id: "2",
    type: "call",
    title: "Follow-up call completed",
    description: "David Kim — Coastal Family Home negotiation",
    time: "4 hours ago",
    user: "Michael Torres",
  },
  {
    id: "3",
    type: "email",
    title: "Proposal sent",
    description: "Lisa Park — Urban Studio Apartment",
    time: "Yesterday",
    user: "Sarah Chen",
  },
  {
    id: "4",
    type: "meeting",
    title: "Client meeting",
    description: "Maria Gonzalez — Investment portfolio review",
    time: "Yesterday",
    user: "Michael Torres",
  },
  {
    id: "5",
    type: "note",
    title: "Deal closed",
    description: "Suburban Estate — Kevin O'Brien",
    time: "2 days ago",
    user: "Emily Watson",
  },
]

export const tasks: Task[] = [
  {
    id: "1",
    title: "Send contract to James Rodriguez",
    dueDate: "Today",
    priority: "high",
    relatedTo: "Modern Downtown Loft",
    completed: false,
  },
  {
    id: "2",
    title: "Schedule property appraisal",
    dueDate: "Tomorrow",
    priority: "medium",
    relatedTo: "Coastal Family Home",
    completed: false,
  },
  {
    id: "3",
    title: "Update listing photos",
    dueDate: "Mar 20",
    priority: "low",
    relatedTo: "Lakefront Villa",
    completed: false,
  },
  {
    id: "4",
    title: "Prepare closing documents",
    dueDate: "Mar 22",
    priority: "high",
    relatedTo: "Urban Studio Apartment",
    completed: false,
  },
]
